### ISSUE TITLE
Test on custom dataset.

### ISSUE THREAD

**Issue by Jihyun0510** [junxuan-li/SCPS-NIR#1]
hello
Thanks for your great work!

While testing on my custom dataset, I encountered a problem 

```
Start testing diligent
Found pretrain light model checkpoints:  runs/pre_trained_LNet/model_params.pth
Found checkpoints ./runs/diligent/Woodenbowl/model_params_02000.pth
Traceback (most recent call last):
  File "train.py", line 552, in <module>
    optimizer.load_state_dict(ckpt['optimizer_state_dict'])
  File "/home/wgus5950/miniconda3/envs/scps_nir/lib/python3.8/site-packages/torch/optim/optimizer.py", line 146, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
```
I think this occured while erasing some of the parameters that my dataset do not contain.
Our custom dataset contain only input images and GT normal image but not light directions nor light intensity.

How do you run your code with a dataset that do not have light direction and intensity information??

Thank you so much

**Comment by junxuan-li** [comment]
You don't need to change any code for unknown light sources. Our code, by default, assumes no knowledge of the light directions and intensities. I will explain how our code works to solve the lights below:

In the code, we first initialize the light directions and light intensities as explicit parameters in light model:
```
Initial light directions and light intensity:
https://github.com/junxuan-li/SCPS-NIR/blob/775db12dea996a6a04af46582b3e60422bcba776/train.py#L513
```

Then the pre-trained light model is called to initialize the light directions and light intensities:
```
Coarse light estimation from pre-trained light models: 
https://github.com/junxuan-li/SCPS-NIR/blob/775db12dea996a6a04af46582b3e60422bcba776/train.py#L54
```

Later, during the training, the networks will keep updating the light directions and light intensities in light model to refine the initializations.

**Comment by Jihyun0510** [comment]
Problem solved!

Thanks so much for your reply:)

**Comment by air55555** [comment]
Hi @Jihyun0510 , seems we need to set these params in yaml  for unknown ligths ? 
light_model:
    explicit_direction: false
    explicit_intensity: false
Or smthing else? the readme can't provide exact details on how to work with unknown lighting .
