### ISSUE TITLE
How to achieve the same level of accuracy as in the paper?

### ISSUE THREAD

**Issue by Masahiro1002** [junxuan-li/SCPS-NIR#2]
Thank you for sharing your code.

I have a question about the evaluation result of DiLiGenT dataset in the paper.
I have trained from scratch on the DiLiGenT dataset and have not been able to achieve the same level of accuracy as the paper. However, I used the weights you shared and am getting the same accuracy results as the paper. Are the settings in this repository different from the ones used to obtain the results in Table 3 of the paper?
Also, do you have any advice on how to obtain the results in Table 3 of the paper?

These are the normal estimation results I got.
|ball|bear|buddha|cat|cow|goblet|harvest|Pot1|pot2|reading|avg|
|---|---|---|---|---|---|---|---|---|---|---|
|1.62|3.99|9.28|7.06|6.43|9.22|15.21|9.00|6.38|11.67|7.99|

Thank you.

**Comment by wh017** [comment]
I encountered the same problem as you and my normal estimation results were:
nml_mae1.684 3.859 9.584 7.217 6.436 9.056 14.989 9.161 6.285 11.604 7.988(avg)
Have you solved it?

**Comment by Masahiro1002** [comment]
No, I haven’t. I tried adjusting various parameters but could not reproduce the results.
